name: splitwise_pro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  google_fonts: ^6.1.0
  get: ^4.6.6
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "272727"
  image:
    -assets/images/google.png
  image_dark:
    -assets/images/google.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/onboarding_images/
    - assets/images/welcome_images/
    - assets/logo/
  uses-material-design: true
